# Central Intelligence Router Configuration
# Configuration for the Central Intelligence Router that monitors and routes agent communication
# Enhanced with CIL management capabilities for organic team coordination

router:
  # Monitoring settings
  monitoring:
    enabled: true
    check_interval_seconds: 30
    message_lookback_minutes: 5
    max_messages_per_check: 100
    
  # Routing settings
  routing:
    min_confidence_threshold: 0.4
    max_agents_per_route: 5
    similarity_threshold: 0.7
    max_similar_patterns: 10
    
  # Performance tracking
  performance:
    track_routing_stats: true
    update_agent_status_interval_minutes: 60
    inactive_agent_threshold_hours: 2
    
  # Logging
  logging:
    level: "INFO"
    log_routing_decisions: true
    log_agent_discoveries: true
    log_performance_updates: true

# Agent capability registration
agent_registration:
  # Default capabilities for common agent types
  default_capabilities:
    pattern_detector:
      capabilities: ["pattern_detection", "signal_detection", "technical_analysis"]
      specializations: ["rsi_analysis", "macd_analysis", "bollinger_analysis"]
    
    threshold_manager:
      capabilities: ["threshold_management", "parameter_control", "system_control"]
      specializations: ["signal_thresholds", "confidence_thresholds", "risk_thresholds"]
    
    parameter_optimizer:
      capabilities: ["parameter_optimization", "weight_optimization", "performance_analysis"]
      specializations: ["feature_weights", "scoring_weights", "clustering_parameters"]
    
    learning_agent:
      capabilities: ["learning", "lesson_generation", "pattern_clustering"]
      specializations: ["strand_clustering", "braid_creation", "lesson_synthesis"]
    
    raw_data_intelligence:
      capabilities: ["raw_data_analysis", "market_microstructure", "volume_analysis"]
      specializations: ["ohlcv_patterns", "volume_spikes", "time_based_patterns"]
    
    indicator_intelligence:
      capabilities: ["indicator_analysis", "divergence_detection", "momentum_analysis"]
      specializations: ["rsi_divergences", "macd_signals", "bollinger_breakouts"]
    
    # CIL Team capabilities
    central_intelligence_layer:
      capabilities: ["strategic_analysis", "experiment_orchestration", "doctrine_management", "plan_composition", "resonance_management"]
      specializations: ["cross_team_patterns", "strategic_experiments", "doctrine_curation", "strategic_plans", "resonance_calculation"]
      management_capabilities: ["experiment_assignment", "directive_issuance", "team_coordination", "resource_allocation"]

# Content type mappings
content_type_mappings:
  pattern_detection:
    required_capabilities: ["pattern_detection", "signal_detection"]
    preferred_capabilities: ["pattern_analysis", "technical_analysis"]
    excluded_capabilities: []
    priority_agents: []
    
  threshold_management:
    required_capabilities: ["threshold_management", "parameter_control"]
    preferred_capabilities: ["system_control", "optimization"]
    excluded_capabilities: []
    priority_agents: []
    
  parameter_optimization:
    required_capabilities: ["parameter_optimization", "weight_optimization"]
    preferred_capabilities: ["system_control", "performance_analysis"]
    excluded_capabilities: []
    priority_agents: []
    
  performance_analysis:
    required_capabilities: ["performance_analysis", "learning"]
    preferred_capabilities: ["optimization", "feedback_analysis"]
    excluded_capabilities: []
    priority_agents: []
    
  learning_opportunity:
    required_capabilities: ["learning", "lesson_generation"]
    preferred_capabilities: ["pattern_clustering", "context_analysis"]
    excluded_capabilities: []
    priority_agents: []
    
  raw_data_intelligence:
    required_capabilities: ["raw_data_analysis", "market_microstructure"]
    preferred_capabilities: ["volume_analysis", "time_based_patterns"]
    excluded_capabilities: []
    priority_agents: []
    
  indicator_intelligence:
    required_capabilities: ["indicator_analysis", "divergence_detection"]
    preferred_capabilities: ["rsi_analysis", "macd_analysis", "bollinger_analysis"]
    excluded_capabilities: []
    priority_agents: []
    
  system_control:
    required_capabilities: ["system_control", "parameter_management"]
    preferred_capabilities: ["threshold_control", "dial_management"]
    excluded_capabilities: []
    priority_agents: []
    
  # CIL Management content types
  cil_management:
    required_capabilities: ["strategic_analysis", "experiment_orchestration"]
    preferred_capabilities: ["cross_team_patterns", "strategic_experiments"]
    excluded_capabilities: []
    priority_agents: ["central_intelligence_layer"]
    
  cil_directives:
    required_capabilities: ["experiment_assignment", "directive_issuance"]
    preferred_capabilities: ["team_coordination", "resource_allocation"]
    excluded_capabilities: []
    priority_agents: ["central_intelligence_layer"]
    
cil_meta_signals:
  required_capabilities: ["strategic_analysis", "cross_team_patterns"]
  preferred_capabilities: ["resonance_management", "doctrine_management"]
  excluded_capabilities: []
  priority_agents: ["central_intelligence_layer"]
  
uncertainty_resolution:
  required_capabilities: ["uncertainty_analysis", "resolution_strategy"]
  preferred_capabilities: ["data_collection", "experiment_design", "human_review"]
  excluded_capabilities: []
  priority_agents: ["central_intelligence_layer", "learning_agent", "system_control"]

# Routing decision weights
routing_weights:
  required_capability_match: 0.4
  preferred_capability_match: 0.2
  specialization_match: 0.15
  performance_boost: 0.1
  priority_agent_boost: 0.1
  excluded_capability_penalty: -0.3

# Agent performance metrics
performance_metrics:
  routing_effectiveness:
    initial_value: 0.5
    min_value: 0.0
    max_value: 1.0
    update_alpha: 0.1  # Exponential moving average smoothing factor
    
  response_time:
    initial_value: 30.0  # seconds
    min_value: 1.0
    max_value: 300.0
    
  success_rate:
    initial_value: 0.5
    min_value: 0.0
    max_value: 1.0
    update_alpha: 0.1

# Database settings
database:
  # Table names
  strands_table: "AD_strands"
  agent_capabilities_table: "agent_capabilities"
  
  # Query settings
  max_query_results: 1000
  query_timeout_seconds: 30
  
  # Connection settings
  connection_pool_size: 10
  connection_timeout_seconds: 10

# Error handling
error_handling:
  max_retries: 3
  retry_delay_seconds: 5
  circuit_breaker_threshold: 10
  circuit_breaker_timeout_seconds: 60
  
# CIL Management Configuration
cil_management:
  # CIL directive tracking
  directive_tracking:
    enabled: true
    track_responses: true
    track_compliance: true
    track_performance: true
    response_timeout_minutes: 60
    compliance_threshold: 0.8
    
  # CIL experiment registry
  experiment_registry:
    enabled: true
    track_active_experiments: true
    track_completed_experiments: true
    track_experiment_outcomes: true
    max_concurrent_experiments: 10
    
  # CIL directive routing (enhanced)
  directive_routing:
    enabled: true
    directive_types: ["experiment_assignment", "focus_directive", "coordination_request", "resource_allocation"]
    target_team_mapping:
      "agent:central_intelligence:experiment_orchestrator:experiment_assigned": ["target_team"]
      "agent:central_intelligence:strategic_pattern_miner:focus_directive": ["target_team"]
      "agent:central_intelligence:doctrine_keeper:coordination_request": ["target_team"]
      "agent:central_intelligence:plan_composer:resource_allocation": ["target_team"]
    
  # CIL meta-signal routing (enhanced)
  meta_signal_routing:
    enabled: true
    meta_signal_types: ["confluence_event", "experiment_directive", "doctrine_update", "strategic_plan", "resonance_cluster"]
    subscription_mapping:
      "agent:central_intelligence:meta:confluence_event": ["raw_data_intelligence", "indicator_intelligence", "pattern_intelligence"]
      "agent:central_intelligence:meta:experiment_directive": ["all_teams"]
      "agent:central_intelligence:meta:doctrine_update": ["all_teams"]
      "agent:central_intelligence:meta:strategic_plan": ["all_teams"]
      "agent:central_intelligence:meta:resonance_cluster": ["system_control", "learning_agent"]
    
  # CIL team coordination
  team_coordination:
    enabled: true
    coordination_types: ["sequential", "parallel", "dependent"]
    conflict_resolution: "cil_arbitration"
    resource_allocation: "cil_managed"
    priority_override: "cil_authority"
    
  # Uncertainty-driven review system
  uncertainty_routing:
    enabled: true
    uncertainty_types: ["pattern_clarity", "causal_clarity", "analogy_confidence", "data_sufficiency", "transfer_feasibility"]
    resolution_mapping:
      "pattern_clarity":
        - "data_collection"
        - "experiment_design" 
        - "human_review"
        - "pattern_validation"
      "causal_clarity":
        - "causal_analysis"
        - "counterfactual_testing"
        - "mechanism_research"
        - "causal_validation"
      "analogy_confidence":
        - "analogy_validation"
        - "transfer_testing"
        - "cross_context_analysis"
        - "similarity_validation"
      "data_sufficiency":
        - "data_collection"
        - "sample_expansion"
        - "context_broadening"
        - "data_validation"
      "transfer_feasibility":
        - "transfer_validation"
        - "context_mapping"
        - "transformation_testing"
        - "feasibility_analysis"
    priority_thresholds:
      high_priority: 0.8
      medium_priority: 0.5
      low_priority: 0.2
    action_triggers:
      immediate_action: 0.9
      scheduled_review: 0.7
      background_monitoring: 0.3

# Security settings
security:
  validate_agent_identity: true
  require_agent_registration: true
  max_message_size_bytes: 1048576  # 1MB
  rate_limit_messages_per_minute: 100
