# Context Injection Configuration
# Defines how each module gets context from the learning system

# Module Subscriptions - which strand types each module subscribes to
module_subscriptions:
  rdi:
    name: "Raw Data Intelligence"
    subscribed_strand_types: []
    context_sources: []
    description: "RDI creates patterns but doesn't consume context from other modules"
    
  cil:
    name: "Central Intelligence Layer"
    subscribed_strand_types: 
      - "prediction_review"
      - "pattern_overview"
    context_sources:
      - "prediction_review_braids"
      - "pattern_braids"
    context_priority: "high"
    max_context_items: 10
    description: "CIL gets context from prediction reviews and pattern overviews for better predictions"
    
  ctp:
    name: "Conditional Trading Planner"
    subscribed_strand_types:
      - "prediction_review"
      - "trade_outcome"
    context_sources:
      - "prediction_review_braids"
      - "trade_outcome_braids"
    context_priority: "high"
    max_context_items: 15
    description: "CTP gets context from predictions and trade outcomes to create better plans"
    
  dm:
    name: "Decision Maker"
    subscribed_strand_types:
      - "conditional_trading_plan"
      - "portfolio_outcome"
      - "trading_decision"
    context_sources:
      - "conditional_trading_plan_braids"
      - "portfolio_outcome_braids"
      - "trading_decision_braids"
    context_priority: "high"
    max_context_items: 10
    description: "DM gets context from trading plans, portfolio outcomes, and past decisions for better risk assessment and budget allocation"
    
  td:
    name: "Trader"
    subscribed_strand_types:
      - "trading_decision"
      - "execution_outcome"
      - "pattern"
    context_sources:
      - "trading_decision_braids"
      - "execution_outcome_braids"
      - "pattern_braids"
    context_priority: "high"
    max_context_items: 15
    description: "TD gets context from trading decisions, execution outcomes, and pattern detection for better execution quality and pattern monitoring"

# Context Quality Thresholds
quality_thresholds:
  min_braid_level: 2
  min_resonance_score: 0.6
  min_strand_count: 3
  max_age_days: 30

# Context Injection Settings
injection_settings:
  enabled: true
  cache_duration_minutes: 15
  max_context_length: 4000
  compression_enabled: true
  similarity_threshold: 0.7
  
# Context Formatting
context_formatting:
  include_metadata: true
  include_resonance_scores: true
  include_learning_insights: true
  include_performance_metrics: true
  max_insights_per_context: 5

# Module-Specific Context Templates
context_templates:
  cil:
    prediction_context: |
      Based on recent prediction performance:
      - Success Rate: {success_rate}%
      - Key Insights: {insights}
      - Recommended Approaches: {approaches}
      - Patterns to Watch: {patterns}
    
  ctp:
    plan_context: |
      Based on recent trading plan performance:
      - Plan Success Rate: {success_rate}%
      - Profitable Strategies: {strategies}
      - Risk Management Insights: {risk_insights}
      - Market Condition Adaptations: {adaptations}
      - Conditional Logic Effectiveness: {conditional_effectiveness}
    
  dm:
    decision_context: |
      Based on recent decision outcomes:
      - Decision Quality Score: {quality_score}
      - Risk Management Effectiveness: {risk_effectiveness}
      - Portfolio Impact: {portfolio_impact}
      - Budget Allocation Success: {allocation_success}
      - Leverage Decision Accuracy: {leverage_accuracy}
      - Key Decision Factors: {factors}
    
  td:
    execution_context: |
      Based on recent execution performance:
      - Execution Success Rate: {success_rate}%
      - Slippage Performance: {slippage_performance}
      - Timing Insights: {timing_insights}
      - Venue Performance: {venue_performance}
      - Pattern Recognition Accuracy: {pattern_accuracy}
      - Conditional Action Execution: {conditional_execution}
