# Tag Convention System Configuration
# Standardized tagging system for agent communication

tag_conventions:
  # Tag structure definitions
  structures:
    agent_routing:
      pattern: "agent:([^:]+):routed_from:([^:]+):(.+)"
      description: "Tag for messages routed by the Central Intelligence Router"
      example: "agent:threshold_manager:routed_from:strand_123:pattern_detected"
      required_fields: ["target_agent", "source_strand_id", "routing_reason"]
      optional_fields: ["priority", "content_type"]
      
    agent_direct:
      pattern: "agent:([^:]+):([^:]+):from:([^:]+)"
      description: "Tag for direct agent-to-agent communication"
      example: "agent:threshold_manager:threshold_analysis:from:pattern_detector"
      required_fields: ["target_agent", "action_type", "source_agent"]
      optional_fields: ["priority", "message_id"]
      
    system_wide:
      pattern: "system:([^:]+)(?::(.+))?"
      description: "Tag for system-wide messages and alerts"
      example: "system:escalation_required:performance_degradation"
      required_fields: ["system_action"]
      optional_fields: ["details", "priority"]
      
    intelligence_level:
      pattern: "intelligence:([^:]+):([^:]+)(?::(.+))?"
      description: "Tag for intelligence level communication"
      example: "intelligence:raw_data:pattern_detected:volume_spike"
      required_fields: ["intelligence_level", "action_type"]
      optional_fields: ["details", "confidence"]
      
    message_type:
      pattern: "message:([^:]+)(?::(.+))?"
      description: "Tag for message type classification"
      example: "message:action_required:threshold_update"
      required_fields: ["message_type"]
      optional_fields: ["subtype", "priority"]
      
    priority:
      pattern: "priority:([^:]+)"
      description: "Tag for message priority"
      example: "priority:urgent"
      required_fields: ["priority_level"]
      optional_fields: []
      
    content_type:
      pattern: "content:([^:]+)(?::(.+))?"
      description: "Tag for content type classification"
      example: "content:pattern_detection:rsi_divergence"
      required_fields: ["content_type"]
      optional_fields: ["subtype", "details"]
      
    response:
      pattern: "response:([^:]+):to:([^:]+)"
      description: "Tag for response messages"
      example: "response:acknowledgment:to:message_456"
      required_fields: ["response_type", "original_message_id"]
      optional_fields: ["responding_agent"]
      
    escalation:
      pattern: "escalation:([^:]+)(?::(.+))?"
      description: "Tag for escalation messages"
      example: "escalation:performance_alert:threshold_breach"
      required_fields: ["escalation_type"]
      optional_fields: ["details", "severity"]

# Tag validation rules
validation:
  # General validation
  general:
    max_tag_length: 500
    min_tag_length: 5
    allowed_characters: "a-zA-Z0-9:_-"
    case_sensitive: false
    
  # Required tag components
  required_components:
    agent_routing: ["agent", "target_agent", "routed_from", "source_strand_id", "routing_reason"]
    agent_direct: ["agent", "target_agent", "action_type", "from", "source_agent"]
    system_wide: ["system", "system_action"]
    intelligence_level: ["intelligence", "intelligence_level", "action_type"]
    message_type: ["message", "message_type"]
    priority: ["priority", "priority_level"]
    content_type: ["content", "content_type"]
    response: ["response", "response_type", "to", "original_message_id"]
    escalation: ["escalation", "escalation_type"]
    
  # Field validation
  field_validation:
    agent_name:
      pattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
      min_length: 2
      max_length: 50
      
    priority_level:
      allowed_values: ["low", "normal", "high", "urgent"]
      case_sensitive: false
      
    message_type:
      allowed_values: ["information", "action_required", "escalation", "performance_alert", "learning_opportunity", "system_control", "response", "error"]
      case_sensitive: false
      
    response_type:
      allowed_values: ["acknowledgment", "action_taken", "escalation", "error"]
      case_sensitive: false
      
    intelligence_level:
      allowed_values: ["raw_data", "indicator", "pattern", "system"]
      case_sensitive: false

# Tag parsing settings
parsing:
  # Parsing behavior
  behavior:
    case_sensitive: false
    trim_whitespace: true
    normalize_case: true
    
  # Error handling
  error_handling:
    strict_parsing: false
    allow_partial_matches: true
    return_parse_errors: true
    
  # Performance
  performance:
    cache_compiled_patterns: true
    max_cache_size: 1000
    cache_ttl_seconds: 3600

# Tag generation settings
generation:
  # Default values
  defaults:
    priority: "normal"
    content_type: "general"
    message_type: "information"
    
  # Tag composition
  composition:
    use_standard_order: true
    include_optional_fields: true
    max_optional_fields: 3
    
  # Tag formatting
  formatting:
    use_underscores: false
    use_hyphens: false
    use_colons: true
    separator: ":"

# Tag examples and templates
examples:
  # Common tag examples
  common:
    agent_routing: "agent:threshold_manager:routed_from:strand_123:pattern_detected:priority:high"
    agent_direct: "agent:pattern_detector:threshold_analysis:from:raw_data_intelligence:priority:normal"
    system_wide: "system:escalation_required:performance_degradation:priority:urgent"
    intelligence_level: "intelligence:raw_data:pattern_detected:volume_spike:confidence:0.85"
    message_type: "message:action_required:threshold_update:priority:high"
    priority: "priority:urgent"
    content_type: "content:pattern_detection:rsi_divergence:details:bullish"
    response: "response:acknowledgment:to:message_456:from:threshold_manager"
    escalation: "escalation:performance_alert:threshold_breach:severity:high"
    
  # Template patterns
  templates:
    agent_routing: "agent:{target_agent}:routed_from:{source_strand_id}:{routing_reason}"
    agent_direct: "agent:{target_agent}:{action_type}:from:{source_agent}"
    system_wide: "system:{system_action}"
    intelligence_level: "intelligence:{intelligence_level}:{action_type}"
    message_type: "message:{message_type}"
    priority: "priority:{priority_level}"
    content_type: "content:{content_type}"
    response: "response:{response_type}:to:{original_message_id}"
    escalation: "escalation:{escalation_type}"

# Tag usage guidelines
guidelines:
  # Best practices
  best_practices:
    - "Use descriptive and specific tag names"
    - "Include relevant context in optional fields"
    - "Use consistent naming conventions"
    - "Avoid overly complex tag structures"
    - "Include priority information when relevant"
    
  # Common mistakes
  common_mistakes:
    - "Using inconsistent case (should be lowercase)"
    - "Missing required fields"
    - "Using invalid characters"
    - "Creating overly long tags"
    - "Not following standard patterns"
    
  # Performance considerations
  performance:
    - "Keep tags as short as possible while remaining descriptive"
    - "Use standard patterns for better parsing performance"
    - "Avoid nested or deeply structured tags"
    - "Cache frequently used tag patterns"

# Tag monitoring and analytics
monitoring:
  # Tag usage tracking
  usage_tracking:
    track_tag_frequency: true
    track_tag_patterns: true
    track_tag_errors: true
    track_tag_performance: true
    
  # Analytics
  analytics:
    generate_usage_reports: true
    report_interval_hours: 24
    identify_popular_patterns: true
    identify_error_patterns: true
    
  # Alerts
  alerts:
    alert_on_tag_errors: true
    alert_on_invalid_patterns: true
    alert_on_performance_issues: true
    max_errors_per_hour: 100

