# Trading Plan Configuration
# Phase 1.4.6: Configuration and Risk Management

risk_management:
  high_confidence:
    max_position_size: 0.15
    risk_per_trade: 0.03
    min_risk_reward: 1.5
    max_risk_reward: 3.0
    stop_loss_atr_multiplier: 2.0
    take_profit_atr_multiplier: 4.0
  medium_confidence:
    max_position_size: 0.10
    risk_per_trade: 0.02
    min_risk_reward: 1.5
    max_risk_reward: 2.5
    stop_loss_atr_multiplier: 1.5
    take_profit_atr_multiplier: 3.0
  low_confidence:
    max_position_size: 0.05
    risk_per_trade: 0.01
    min_risk_reward: 2.0
    max_risk_reward: 2.0
    stop_loss_atr_multiplier: 1.0
    take_profit_atr_multiplier: 2.0

position_sizing:
  base_percentage: 0.05
  max_percentage: 0.15
  volatility_adjustment: true
  correlation_adjustment: true
  kelly_criterion: false  # For future implementation
  fixed_fractional: true  # Current method

time_horizons:
  '1m': '5m'
  '5m': '15m'
  '15m': '1h'
  '1h': '4h'
  '4h': '1d'
  '1d': '1w'

entry_strategies:
  market_order: 'immediate'
  limit_order: 'price_improvement'
  stop_order: 'breakout_confirmation'
  default: 'limit_order'

execution_venues:
  primary: 'hyperliquid'
  backup: 'binance'
  fallback: 'coinbase'

order_types:
  market: 'immediate_execution'
  limit: 'price_improvement'
  stop: 'breakout_confirmation'
  stop_limit: 'controlled_execution'

time_in_force:
  GTC: 'good_till_cancelled'
  IOC: 'immediate_or_cancel'
  FOK: 'fill_or_kill'
  default: 'GTC'

slippage_tolerance:
  high_volatility: 0.005  # 0.5%
  medium_volatility: 0.003  # 0.3%
  low_volatility: 0.001  # 0.1%
  default: 0.003

execution_priority:
  high: 'urgent_execution'
  medium: 'normal_execution'
  low: 'patient_execution'
  default: 'medium'

# Signal strength thresholds for risk configuration selection
signal_thresholds:
  high_confidence: 0.8
  medium_confidence: 0.6
  low_confidence: 0.4

# Market context weights for position sizing
market_context_weights:
  volatility: 0.3
  trend_strength: 0.2
  volume_confirmation: 0.2
  pattern_strength: 0.2
  regime_alignment: 0.1

# Risk limits
risk_limits:
  max_total_exposure: 0.5  # 50% of portfolio
  max_correlation_exposure: 0.3  # 30% in correlated assets
  max_daily_loss: 0.05  # 5% daily loss limit
  max_drawdown: 0.15  # 15% maximum drawdown

# Validation rules
position_sizing:
  base_position_size: 0.05
  max_position_size: 0.20
  position_size_multiplier: 1.0

time_horizons:
  short_term: 1
  medium_term: 4
  long_term: 24

signal_thresholds:
  min_confidence: 0.6
  min_strength: 0.5
  min_volume_ratio: 1.2
  min_rsi_divergence: 10

validation:
  min_entry_price: 0.01
  max_entry_price: 1000000
  min_position_size: 0.001
  max_position_size: 1.0
  min_risk_reward: 1.0
  max_risk_reward: 10.0
  min_confidence: 0.1
  max_confidence: 1.0
  min_strength: 0.1
  max_strength: 1.0
