-- PM Overrides Database Schema
-- Active overrides applied at runtime.
-- Source: Generated by Materializer from Learning Lessons.
-- Usage: PM Core Tick queries this to adjust sizing/execution.

-- Drop existing table if it exists
DROP TABLE IF EXISTS pm_overrides CASCADE;

-- Create pm_overrides table
CREATE TABLE pm_overrides (
    id BIGSERIAL PRIMARY KEY,
    pattern_key TEXT NOT NULL,                      -- Canonical pattern
    action_category TEXT NOT NULL,                  -- "entry", "trim" (or "any")
    scope_subset JSONB NOT NULL,                    -- The slice: {"chain": "solana"}
    multiplier FLOAT NOT NULL DEFAULT 1.0,          -- The sizing multiplier (e.g. 1.15)
    
    -- Optional: Tuning params (if we move beyond just size multiplier)
    tuning_params JSONB,                            -- { "ts_min": 0.6, "entry_delay": 1 }
    
    -- Metadata
    confidence_score FLOAT,                         -- How confident are we? (based on N/Variance)
    decay_state TEXT,                               -- "stable", "decaying", "growing"
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    UNIQUE (pattern_key, action_category, scope_subset)
);

-- Indexes
CREATE INDEX idx_pm_overrides_lookup ON pm_overrides(pattern_key, action_category);
CREATE INDEX idx_pm_overrides_subset ON pm_overrides USING GIN(scope_subset);

-- Comments
COMMENT ON TABLE pm_overrides IS 'Active PM runtime overrides. Generated by the Learning Materializer.';

