# Agent Communication Protocol Configuration
# Configuration for standardized agent communication through the database

communication:
  # Protocol settings
  protocol:
    version: "1.0"
    message_timeout_seconds: 300  # 5 minutes
    response_timeout_seconds: 60  # 1 minute
    max_message_size_bytes: 1048576  # 1MB
    
  # Message handling
  message_handling:
    default_handlers:
      information: "handle_information_message"
      action_required: "handle_action_required_message"
      escalation: "handle_escalation_message"
      performance_alert: "handle_performance_alert_message"
      learning_opportunity: "handle_learning_opportunity_message"
      system_control: "handle_system_control_message"
    
    # Message type priorities
    message_priorities:
      urgent: 1
      high: 2
      normal: 3
      low: 4
    
    # Message expiration
    message_expiration:
      default_expiration_minutes: 60
      urgent_expiration_minutes: 15
      high_expiration_minutes: 30
      normal_expiration_minutes: 60
      low_expiration_minutes: 120

# Agent settings
agent:
  # Agent identification
  identification:
    require_agent_name: true
    validate_agent_name: true
    agent_name_pattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
    
  # Agent capabilities
  capabilities:
    auto_register_capabilities: true
    capability_validation: true
    max_capabilities_per_agent: 20
    max_specializations_per_agent: 50
    
  # Agent status
  status:
    active_status_timeout_minutes: 120
    inactive_status_timeout_minutes: 240
    error_status_timeout_minutes: 60

# Listening settings
listening:
  # Message polling
  polling:
    enabled: true
    interval_seconds: 10
    batch_size: 50
    lookback_minutes: 2
    
  # Message filtering
  filtering:
    filter_expired_messages: true
    filter_duplicate_messages: true
    max_duplicate_check_minutes: 5
    
  # Message processing
  processing:
    max_concurrent_messages: 10
    message_processing_timeout_seconds: 30
    retry_failed_messages: true
    max_retry_attempts: 3

# Response handling
response:
  # Response tracking
  tracking:
    track_response_times: true
    track_response_success: true
    max_pending_responses: 100
    
  # Response callbacks
  callbacks:
    default_callback_timeout_seconds: 60
    max_callback_wait_time_minutes: 10
    
  # Response validation
  validation:
    validate_response_format: true
    require_response_id: true
    require_original_message_id: true

# Tag system
tags:
  # Tag validation
  validation:
    validate_tag_format: true
    require_standard_tags: true
    max_tag_length: 500
    
  # Tag parsing
  parsing:
    case_sensitive: false
    allow_custom_tags: true
    max_custom_tags: 5
    
  # Tag conventions
  conventions:
    use_standard_conventions: true
    enforce_tag_structure: true
    validate_tag_content: true

# Performance monitoring
performance:
  # Metrics collection
  metrics:
    collect_message_stats: true
    collect_response_stats: true
    collect_error_stats: true
    collect_performance_stats: true
    
  # Performance thresholds
  thresholds:
    max_message_processing_time_seconds: 30
    max_response_time_seconds: 60
    max_error_rate_percent: 10
    min_success_rate_percent: 80
    
  # Performance reporting
  reporting:
    report_interval_minutes: 15
    log_performance_metrics: true
    alert_on_threshold_breach: true

# Error handling
error_handling:
  # Error types
  error_types:
    message_parse_error: "warning"
    message_validation_error: "error"
    response_timeout_error: "warning"
    agent_not_found_error: "error"
    capability_mismatch_error: "warning"
    
  # Error recovery
  recovery:
    auto_retry_on_error: true
    max_retry_attempts: 3
    retry_delay_seconds: 5
    exponential_backoff: true
    
  # Error logging
  logging:
    log_all_errors: true
    log_error_details: true
    log_error_context: true

# Security settings
security:
  # Message security
  message_security:
    validate_message_source: true
    require_agent_authentication: true
    encrypt_sensitive_content: false  # Can be enabled if needed
    
  # Access control
  access_control:
    restrict_agent_communication: false
    allow_cross_agent_messages: true
    require_agent_registration: true
    
  # Rate limiting
  rate_limiting:
    enabled: true
    max_messages_per_minute: 100
    max_messages_per_hour: 1000
    burst_limit: 20

# Database settings
database:
  # Table configuration
  tables:
    strands_table: "AD_strands"
    agent_capabilities_table: "agent_capabilities"
    message_log_table: "agent_message_log"
    
  # Query settings
  queries:
    max_query_results: 1000
    query_timeout_seconds: 30
    use_connection_pooling: true
    
  # Transaction settings
  transactions:
    use_transactions: true
    transaction_timeout_seconds: 60
    auto_rollback_on_error: true

# Logging configuration
logging:
  # Log levels
  levels:
    communication: "INFO"
    message_handling: "INFO"
    response_handling: "INFO"
    error_handling: "WARNING"
    performance: "INFO"
    
  # Log formatting
  formatting:
    include_timestamps: true
    include_agent_names: true
    include_message_ids: true
    include_performance_metrics: true
    
  # Log rotation
  rotation:
    max_log_size_mb: 100
    max_log_files: 10
    compress_old_logs: true

