# Social Trading System Configuration

# Database Configuration
database:
  url: "postgresql://postgres:password@localhost:5432/lotus_trader"
  schema: "public"

# Social Media Monitoring
social_monitoring:
  twitter:
    enabled: true
    check_interval: 30  # seconds
    curators_file: "src/config/twitter_curators.yaml"
    cookies_file: "src/config/twitter_cookies.json"
  
  telegram:
    enabled: true
    check_interval: 30  # seconds
    session_file: "src/config/telegram_session.txt"
    groups_file: "src/config/telegram_groups.yaml"
    
    # Signal Notifications
    signal_notifications:
      enabled: true
      bot_token: "${TELEGRAM_BOT_TOKEN}"  # Set in environment variables
      channel_id: "${TELEGRAM_CHANNEL_ID}"  # Your private group ID or @username
      api_id: 21826741  # Your existing API ID
      api_hash: "4643cce207a1a9d56d56a5389a4f1f52"  # Your existing API hash

# Trading Configuration
trading:
  book_nav: 100000.0  # $100k book size
  max_exposure_pct: 20.0  # Maximum portfolio exposure
  min_curator_score: 0.6  # Minimum curator score to approve
  # Note: Allocation percentages are now centralized in allocation_config section below

# Centralized Allocation Configuration
# This is the single source of truth for all allocation percentages
allocation_config:
  # Social Media Curators (based on curator score)
  social_curators:
    excellent_score: 0.8  # Score threshold for excellent curators
    excellent_allocation: 15.0  # 15% for excellent curators (score >= 0.8)
    good_score: 0.6  # Score threshold for good curators
    good_allocation: 6.0  # 6% for good curators (score >= 0.6)
    acceptable_allocation: 4.0  # 4% for acceptable curators (score < 0.6)
  
  # Gem Bot Signals
  gem_bot:
    conservative_allocation: 6.0  # 6% for conservative gem bot signals
    balanced_allocation: 4.0  # 4% for balanced gem bot signals
    risky_allocation: 2.0  # 2% for risky gem bot signals
  
  # Test Mode (reduced allocations for safe testing)
  test_mode:
    social_curators_multiplier: 0.1  # 10% of normal allocation
    gem_bot_multiplier: 0.2  # 20% of normal allocation

# Position Management
position_management:
  price_check_interval: 60  # seconds
  exit_check_interval: 30   # seconds
  dip_entry_check_interval: 10  # seconds
  
  # Entry Strategy
  entry_strategy:
    entry_1:  # Immediate entry
      allocation_pct: 33.33
    entry_2:  # -38.2% dip
      allocation_pct: 33.33
      dip_pct: -38.2
    entry_3:  # -61.8% dip
      allocation_pct: 33.34
      dip_pct: -61.8
  
  # Exit Strategy (30% of remaining at each level)
  exit_strategy:
    exit_1:
      gain_pct: 38.2
      exit_pct: 30
    exit_2:
      gain_pct: 61.8
      exit_pct: 30
    exit_3:
      gain_pct: 161.8
      exit_pct: 30
    exit_4:
      gain_pct: 261.8
      exit_pct: 30
    exit_5:
      gain_pct: 361.8
      exit_pct: 30
    exit_6:
      gain_pct: 561.8
      exit_pct: 30
    exit_7:
      gain_pct: 761.8
      exit_pct: 30
    exit_8:
      gain_pct: 1061.8
      exit_pct: 30
    final:
      gain_pct: 1590.0
      exit_pct: 100

  # Trend Strategy (spawned from each standard exit)
  trend_strategy:
    entry_capital_pct: 15  # % of standard exit proceeds allocated to dip buys
    entries:
      - dip_pct: -22    # 78.6% of exit price
        allocation_pct: 50
      - dip_pct: -39    # 61.8% of exit price
        allocation_pct: 50
    exits:  # Sell 70% total across these three
      - gain_pct: 0      # 100% of exit price (break-even)
        exit_pct: 23.33
      - gain_pct: 38.2   # 138.2% of exit price
        exit_pct: 23.33
      - gain_pct: 61.8   # 161.8% of exit price
        exit_pct: 23.34

# Learning System
learning:
  enabled: true
  strand_processing_interval: 5  # seconds
  braid_creation_threshold: 0.7
  min_cluster_size: 2

# LLM Configuration
llm:
  model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 500
  prompt_templates_dir: "src/llm_integration/prompt_templates"

# DEX Configuration
dex:
  solana:
    default_venue: "Raydium"
    venues: ["Raydium", "Orca", "Jupiter"]
    max_slippage_pct: 5.0
    min_liquidity_usd: 10000
  
  ethereum:
    default_venue: "Uniswap"
    venues: ["Uniswap", "SushiSwap", "1inch"]
    max_slippage_pct: 3.0
    min_liquidity_usd: 50000

# Logging
logging:
  level: "INFO"
  file: "social_trading.log"
  max_size_mb: 100
  backup_count: 5

# Lotus Token Buyback
lotus_buyback:
  enabled: true
  lotus_contract: "Ch4tXj2qf8V6a4GdpS4X3pxAELvbnkiKTHGdmXjLEXsC"
  holding_wallet: "AbumtzzxomWWrm9uypY6ViRgruGdJBPFPM2vyHewTFdd"
  percentage: 10.0  # 10% of every SOL exit
  min_amount_sol: 0.001  # Minimum SOL amount to trigger buyback
  slippage_pct: 2.0  # Slippage tolerance for Jupiter swaps

# Monitoring & Alerts
monitoring:
  health_check_interval: 300  # seconds
  alert_webhook: null  # Discord/Slack webhook for alerts
  performance_tracking: true
  error_reporting: true
